language: php
os: linux
dist: trusty

env:

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files
    - tmp/pear/download/
    - vendor/

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

services:
  - mysql
  - postgresql

before_install:
  - mkdir -p build/logs
  - if [[ "${TRAVIS_PHP_VERSION:0:1}" == "7" ]] || [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - phpenv rehash
  - sh -c "psql -c 'DROP DATABASE IF EXISTS tests;' -U postgres"
  - sh -c "psql -c 'DROP DATABASE IF EXISTS tests2;' -U postgres"
  - sh -c "psql -c 'CREATE DATABASE tests;' -U postgres"
  - sh -c "psql -c 'CREATE DATABASE tests2;' -U postgres"

install:
  - travis_retry composer selfupdate
  - travis_retry composer install --no-interaction --prefer-source --ansi -o -v

before_script:
  - psql tests < tests/psql.sql
  - mysql --default-character-set=utf8mb4 < tests/mysql.sql

script:
  - if [[ "${TRAVIS_PHP_VERSION:0:1}" == "7" ]]; then DBUSER=postgres DBHOST=localhost DBNAME=tests phpdbg -qrr vendor/bin/phpunit -c phpunit.xml.dist tests/Pgsql -v --coverage-clover coverage_pgsql.xml --whitelist src/; fi;
  - if [[ "$(echo "${TRAVIS_PHP_VERSION:0:3}"|grep "5\.[4-5]")" != "" ]]; then DBUSER=postgres DBHOST=localhost DBNAME=tests vendor/bin/phpunit -c phpunit.xml.dist tests/Pgsql -v --coverage-clover coverage_pgsql.xml; fi
  - if [[ "$(echo "${TRAVIS_PHP_VERSION:0:3}"|grep "5\.[4-5]")" == "" ]] && [[ "${TRAVIS_PHP_VERSION:0:1}" != "7" ]]; then DBUSER=postgres DBHOST=localhost DBNAME=tests vendor/bin/phpunit -c phpunit.xml.dist tests/Pgsql -v --coverage-clover coverage_pgsql.xml --whitelist src/; fi
  - if [[ "${TRAVIS_PHP_VERSION:0:1}" == "7" ]]; then DBUSER=tests DBPASS=tests DBHOST=localhost DBNAME=tests phpdbg -qrr vendor/bin/phpunit -c phpunit.xml.dist tests/Mysqli -v --coverage-clover coverage.xml --whitelist src/; fi;
  - if [[ "$(echo "${TRAVIS_PHP_VERSION:0:3}"|grep "5\.[4-5]")" != "" ]]; then DBUSER=tests DBPASS=tests DBHOST=localhost DBNAME=tests vendor/bin/phpunit -c phpunit.xml.dist tests/Mysqli -vvvv --debug --coverage-clover coverage.xml; fi
  - if [[ "$(echo "${TRAVIS_PHP_VERSION:0:3}"|grep "5\.[4-5]")" == "" ]] && [[ "${TRAVIS_PHP_VERSION:0:1}" != "7" ]]; then DBUSER=tests DBPASS=tests DBHOST=localhost DBNAME=tests vendor/bin/phpunit -c phpunit.xml.dist tests/Mysqli -v --coverage-clover coverage.xml --whitelist src/; fi

after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then travis_retry vendor/bin/test-reporter --coverage-report=coverage_pgsql.xml; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then travis_retry vendor/bin/test-reporter --coverage-report=coverage.xml; fi
  - travis_retry bash <(curl -s https://codecov.io/bash);
  - travis_retry php vendor/bin/coveralls -v --coverage_clover=coverage.xml || travis_retry php vendor/bin/php-coveralls -v --coverage_clover=coverage_pgsql.xml;
  - travis_retry php vendor/bin/coveralls -v --coverage_clover=coverage.xml || travis_retry php vendor/bin/php-coveralls -v --coverage_clover=coverage.xml;
  - travis_retry php vendor/bin/codacycoverage clover coverage_pgsql.xml;
  - travis_retry php vendor/bin/codacycoverage clover coverage.xml;
