env:
  - DB=mysql
  - DB=postgres
language: php
os: linux
dist: trusty
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - hhvm-nightly
cache:
  directories:
	- $HOME/.composer/cache/files
	- tmp/pear/download/
	- vendor/
addons:
  code_climate:
	repo_token: $CODECLIMATE_REPO_TOKEN
services:
  - mysql
  - postgresql
before_install:
  - mkdir -p build/logs
  - if [[ "$TRAVIS_PHP_VERSION" != "7.2" ]]; then phpenv config-rm xdebug.ini; fi
  - phpenv rehash
install:
  - travis_retry composer self-update
  - composer install --no-interaction --prefer-source
before_script:
  - if [[ "$DB" == "postgres" ]]; then psql -c "DROP DATABASE IF EXISTS tests;"; fi
  - if [[ "$DB" == "postgres" ]]; then psql -c "CREATE DATABASE tests;"; fi
  - if [[ "$DB" == "postgres" ]]; then psql tests < tests.sql;"; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "DROP DATABASE IF EXISTS tests;"
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS tests;"
  - if [[ "$DB" == "mysql" ]]; then mysql -e "GRANT ALL PRIVILEGES ON tests.* to tests@'%' identified by 'tests';"
  - if [[ "$DB" == "mysql" ]]; then mysql -e "FLUSH PRIVILEGES;"
  - if [[ "$DB" == "mysql" ]]; then mysql --default-character-set=utf8mb4 tests < tests/tests.sql
  - travis_retry composer install -o --ansi --no-interaction --dev --prefer-source
script:
  - if [[ "$DB" == "postgres" ]] && [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then DBUSER=postgres DBHOST=localhost DBNAME=tests phpdbg -qrr vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/Pgsql -v --coverage-clover coverage.xml --whitelist src/; fi;
  - if [[ "$DB" == "postgres" ]] && [[ "$TRAVIS_PHP_VERSION" != "7.0" ]]; then DBUSER=postgres DBHOST=localhost DBNAME=tests vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/Pgsql -v; fi
  - if [[ "$DB" == "mysql" ]] && [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then DBUSER=tests DBPASS=tests DBHOST=localhost DBNAME=tests phpdbg -qrr vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/Mysqli -v --coverage-clover coverage.xml --whitelist src/; fi;
  - if [[ "$DB" == "mysql" ]] && [[ "$TRAVIS_PHP_VERSION" != "7.0" ]]; then DBUSER=tests DBPASS=tests DBHOST=localhost DBNAME=tests vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/Mysqli -v; fi
after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then travis_retry vendor/bin/test-reporter --coverage-report=coverage.xml; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then travis_retry bash <(curl -s https://codecov.io/bash); fi;
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then travis_retry php vendor/bin/coveralls -v --coverage_clover=coverage.xml; fi;
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then travis_retry php vendor/bin/codacycoverage clover coverage.xml; fi;
