env:
  - DB=mysql
  - DB=postgres
language: php
os: linux
dist: trusty
sudo: false
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
cache:
  directories:
    - $HOME/.composer/cache/files
    - tmp/pear/download/
    - vendor/
addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
services:
  - mysql
before_install:
  - mkdir -p build/logs
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - travis_retry composer self-update
install:
  - composer install --no-interaction --prefer-source
before_script:
  - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS tests;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "CREATE DATABASE tests;" -U postgres; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS tests; GRANT ALL PRIVILEGES ON tests.* to tests@'%' identified by 'tests'; FLUSH PRIVILEGES; use tests; source tests/tests.sql;"; fi
  - travis_retry composer update --with-dependencies --no-interaction --dev --prefer-source
script: 
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then DBUSER=tests DBPASS=tests DBHOST=localhost DBNAME=tests phpdbg -qrr vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/ -v --coverage-clover coverage.xml --whitelist src/; fi;
  - if [[ "$TRAVIS_PHP_VERSION" != "7.0" ]]; then DBUSER=tests DBPASS=tests DBHOST=localhost DBNAME=tests vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/ -v; fi
after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then travis_retry vendor/bin/test-reporter --coverage-report=coverage.xml; fi
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then travis_retry bash <(curl -s https://codecov.io/bash); fi;
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then travis_retry php vendor/bin/coveralls -v --coverage_clover=coverage.xml; fi;
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" ]]; then travis_retry php vendor/bin/codacycoverage clover coverage.xml; fi;
