language: php
os: linux
dist: trusty

env:
  - DB=mysql
  - DB=postgres

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache/files
    - tmp/pear/download/
    - vendor/

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

services:
  - mysql
  - postgresql

before_install:
  - mkdir -p build/logs
  - if [[ "${TRAVIS_PHP_VERSION:0:1}" == "7" ]] || [[ "$TRAVIS_PHP_VERSION" == "hhvm" ]]; then phpenv config-rm xdebug.ini; fi
  - phpenv rehash
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS tests2;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE tests2;' -U postgres; fi"
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS tests2; CREATE DATABASE IF NOT EXISTS tests; GRANT ALL PRIVILEGES ON tests.* to tests@'%' identified by 'tests'; GRANT ALL PRIVILEGES ON tests2.* to tests@'%' identified by 'tests'; FLUSH PRIVILEGES;"; fi

install:
  - travis_retry composer selfupdate
  - travis_retry composer install --no-interaction --prefer-source --dev --ansi -o

before_script:
  - if [[ "$DB" == "postgres" ]]; then psql tests < tests/psql.sql; fi
  - if [[ "$DB" == "mysql" ]]; then mysql --default-character-set=utf8mb4 tests < tests/mysql.sql; fi

script:
  - if [[ "$DB" == "postgres" ]] && [[ "${TRAVIS_PHP_VERSION:0:1}" == "7" ]]; then DBUSER=postgres DBHOST=localhost DBNAME=tests phpdbg -qrr vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/Pgsql -v --coverage-clover coverage.xml --whitelist src/; fi;
  - if [[ "$DB" == "postgres" ]] && [[ "${TRAVIS_PHP_VERSION:0:3}" == "5.4" ]]; then DBUSER=postgres DBHOST=localhost DBNAME=tests vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/Pgsql -v --coverage-clover coverage.xml; fi
  - if [[ "$DB" == "postgres" ]] && [[ "${TRAVIS_PHP_VERSION:0:3}" != "5.4" ]] && [[ "${TRAVIS_PHP_VERSION:0:1}" != "7" ]]; then DBUSER=postgres DBHOST=localhost DBNAME=tests vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/Pgsql -v --coverage-clover coverage.xml --whitelist src/; fi
  - if [[ "$DB" == "mysql" ]] && [[ "${TRAVIS_PHP_VERSION:0:1}" == "7" ]]; then DBUSER=tests DBPASS=tests DBHOST=localhost DBNAME=tests phpdbg -qrr vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/Mysqli -v --coverage-clover coverage.xml --whitelist src/; fi;
  - if [[ "$DB" == "mysql" ]] && [[ "${TRAVIS_PHP_VERSION:0:3}" == "5.4" ]]; then DBUSER=tests DBPASS=tests DBHOST=localhost DBNAME=tests vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/Mysqli -v --coverage-clover coverage.xml; fi
  - if [[ "$DB" == "mysql" ]] && [[ "${TRAVIS_PHP_VERSION:0:3}" != "5.4" ]] && [[ "${TRAVIS_PHP_VERSION:0:1}" != "7" ]]; then DBUSER=tests DBPASS=tests DBHOST=localhost DBNAME=tests vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/Mysqli -v --coverage-clover coverage.xml --whitelist src/; fi

after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then travis_retry vendor/bin/test-reporter --coverage-report=coverage.xml; fi
  - travis_retry bash <(curl -s https://codecov.io/bash);
  - travis_retry php vendor/php-coveralls/php-coveralls/bin/php-coveralls -v --coverage_clover=coverage.xml || vendor/bin/coveralls -v --coverage_clover=coverage.xml;
  - travis_retry php vendor/bin/codacycoverage clover coverage.xml;
